<!DOCTYPE html>
<html lang="en"><head>
<script src="Group4-Slides_files/libs/clipboard/clipboard.min.js"></script>
<script src="Group4-Slides_files/libs/quarto-html/tabby.min.js"></script>
<script src="Group4-Slides_files/libs/quarto-html/popper.min.js"></script>
<script src="Group4-Slides_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="Group4-Slides_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Group4-Slides_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="Group4-Slides_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.38">

  <title>group4-slides</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="Group4-Slides_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="Group4-Slides_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="Group4-Slides_files/libs/revealjs/dist/theme/quarto-90454075d69b0a13a897001afc486fa0.css">
  <link href="Group4-Slides_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="Group4-Slides_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="Group4-Slides_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="Group4-Slides_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">


<section id="section" class="slide level2 cover-slide" data-background-image="assets/why-topic-matters.png" data-background-size="cover" data-background-opacity="0.22">
<h2></h2>
<div class="cover-panel">
<p><img data-src="assets/hm-logo.png" class="hm-cover-logo"></p>
<div class="cover-title">
<p>H&amp;M Customer Segmentation</p>
</div>
<div class="cover-members">
<p><strong>Group Members:</strong> Michelle Diaz · Frank Renn · Daisy Herandez · Rosarie Maramag · Gigi Brunel</p>
</div>
</div>
</section>
<section id="problem-definition" class="slide level2 problem-slide" data-background-image="assets/problem-definition.png" data-background-size="cover" data-background-opacity="0.18">
<h2>Problem Definition</h2>
<div class="content-panel">
<p><strong>Audience:</strong> H&amp;M marketing, CRM, and merchandising teams.</p>
<p><strong>Problem:</strong> H&amp;M has a large transaction dataset, but raw purchase records do not directly explain which customers are most valuable, how they shop, or when they are most likely to buy.</p>
<p><strong>Project focus:</strong> Use customer segmentation to turn transaction history into actionable marketing insights.</p>
</div>
</section>
<section id="research-objectives" class="slide level2 problem-slide" data-background-image="assets/problem-definition.png" data-background-size="cover" data-background-opacity="0.18">
<h2>Research Objectives</h2>
<div class="content-panel wide-panel">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>AO</th>
<th>Analytics Objective</th>
<th>Team Member</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>AO1</td>
<td>Do customers with different Fashion News subscription statuses exhibit different purchasing behavior?</td>
<td>Gigi</td>
</tr>
<tr class="even">
<td>AO2</td>
<td>Can spending behavior and age help explain which customers are more likely to leave the membership program?</td>
<td>Rosarie</td>
</tr>
<tr class="odd">
<td>AO3</td>
<td>Does the sales channel (online vs.&nbsp;store) relate to spending patterns?</td>
<td>Michelle</td>
</tr>
<tr class="even">
<td>AO4</td>
<td>How can customers be segmented using RFM value?</td>
<td>Frank</td>
</tr>
<tr class="odd">
<td>AO5</td>
<td>Do purchase timing patterns differ across customer segments?</td>
<td>Daisy</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="importance-of-the-topic" class="slide level2 importance-slide" data-background-image="assets/importance-topic.png" data-background-size="cover" data-background-opacity="0.16">
<h2>Importance of the Topic</h2>
<div class="content-panel">
<p>This project gives H&amp;M a practical way to understand customers using real purchase data.</p>
<p>The findings can help the audience:</p>
<ul>
<li>Target high-value customers more effectively</li>
<li>Re-engage inactive or low-frequency customers</li>
<li>Compare online and store behavior</li>
<li>Time campaigns based on segment-level purchase patterns</li>
<li>Support customer-focused decision making</li>
</ul>
</div>
</section>
<section id="why-this-topic-matters" class="slide level2 matters-slide" data-background-image="assets/why-topic-matters.png" data-background-size="cover" data-background-opacity="0.18">
<h2>Why This Topic Matters</h2>
<div class="content-panel">
<p>Customer segmentation helps H&amp;M move from broad marketing to more targeted decisions.</p>
<p>Instead of treating all shoppers the same, the team can identify groups such as high-value loyal customers, occasional buyers, inactive customers, and customers with specific timing or channel preferences.</p>
<p>This can support better promotions, retention strategies, product recommendations, and campaign timing.</p>
</div>
</section>
<section id="population" class="slide level2" data-background-image="assets/importance-topic.png" data-background-size="cover" data-background-opacity="0.16">
<h2>Population</h2>
<div class="content-panel">
<p>The population represented in this dataset is H&amp;M’s online and in-store customer base, captured through their purchase transaction history.</p>
<ul>
<li>Over 1.3 million unique customers</li>
<li>Customer attributes include age, club membership status, and fashion news subscription preference</li>
<li>Over 100,000 distinct products (articles), described by category, garment type, color, and department</li>
<li>Transactions span both online and physical store sales channels</li>
</ul>
</div>
</section>
<section id="sampling-data-collection" class="slide level2 importance-slide" data-background-image="assets/importance-topic.png" data-background-size="cover" data-background-opacity="0.16">
<h2>Sampling / Data Collection</h2>
<div class="content-panel">
<p><strong>Source:</strong> H&amp;M Group, released publicly via a Kaggle competition (Personalized Fashion Recommendations).</p>
<p><strong>Original collection:</strong> Real transaction records logged by H&amp;M’s retail systems across online and store sales channels.</p>
<p><strong>Our approach:</strong> Given the full transaction file’s size (over 31 million records), our group is working with a random sample of transactions, joined with the full customer and article metadata, to make analysis feasible while preserving the overall structure of customer behavior.</p>
</div>
</section>
<section id="data-wrangling" class="slide level2 importance-slide" data-background-image="assets/importance-topic.png" data-background-size="cover" data-background-opacity="0.16">
<h2>Data Wrangling</h2>
<div class="content-panel panel-xs">
<p><strong>From Records to Data</strong></p>
<ul>
<li>Raw data arrives as three separate files: customer metadata, product/article metadata, and transaction records</li>
<li>Given the size of the full transaction file (31M+ records), our group works with a random sample of transactions, joined with the full customer and article tables</li>
<li>Files are imported into R and inspected for structure, column types, and row counts before any cleaning begins</li>
</ul>
<p><strong>Tidying the Data</strong></p>
<ul>
<li>Check each table for missing values (e.g., customer age, price) and decide on an appropriate handling approach (imputation, exclusion, or flagging)</li>
<li>Standardize categorical variables (e.g., sales channel codes, membership status) to consistent, labeled categories</li>
<li>Remove or address any duplicate records</li>
</ul>
<p><strong>Transforming the Data</strong></p>
<ul>
<li>Join transaction data with customer and article metadata using customer_id and article_id as keys</li>
<li>Create derived variables needed for specific RO’s (e.g., total spend per customer, RFM scores, purchase date components)</li>
<li>Aggregate transaction-level data to the customer level where needed for segmentation analysis</li>
</ul>
</div>
</section>
<section id="ao1-predicting-high-spending-customers" class="slide level2 importance-slide" data-background-image="assets/importance-topic.png" data-background-size="cover" data-background-opacity="0.16">
<h2>AO1: Predicting High-Spending Customers</h2>
<div class="content-panel panel-small">
<p><strong>Analytics Objective:</strong><br>
Can customer characteristics and previous purchasing behavior predict whether an H&amp;M customer will become a future high spender?</p>
<p><strong>Lead:</strong> Gigi Brunel</p>
<p><strong>Machine Learning Methods</strong></p>
<ul>
<li>Lasso Logistic Regression</li>
<li>Tuned Decision Tree</li>
<li>Random Forest</li>
<li>XGBoost</li>
</ul>
<p><strong>Outcome:</strong><br>
High Spender · Not High Spender</p>
<p><strong>Business Goal:</strong><br>
Identify customers who are more likely to become high spenders so H&amp;M can provide more relevant promotions and recommendations.</p>
</div>
</section>
<section id="ao1-data-wrangling-model-setup" class="slide level2">
<h2>AO1: Data Wrangling &amp; Model Setup</h2>
<div class="content-panel panel-xs">
<p><strong>Data Wrangling</strong></p>
<ul>
<li>Combined customer data with transaction history</li>
<li>Used pre-July 2020 transactions as predictors</li>
<li>Used later transactions to measure future spending</li>
<li>Created customer-level purchasing features</li>
<li>Defined High Spenders using median future spending</li>
<li>Separated feature and outcome periods to prevent leakage</li>
</ul>
<p><strong>Predictors</strong></p>
<ul>
<li>Fashion News status, age, club membership</li>
<li>Prior transactions and total spending</li>
<li>Average price and unique products</li>
<li>Online purchase share</li>
<li>Days since most recent purchase</li>
</ul>
<p><strong>Model Setup</strong></p>
<ul>
<li>80% training / 20% testing</li>
<li>Stratified by High Spender status</li>
<li>10-fold cross-validation</li>
</ul>
</div>
</section>
<section id="ao1-prediction-model-evaluation" class="slide level2 importance-slide" data-background-image="assets/importance-topic.png" data-background-size="cover" data-background-opacity="0.16">
<h2>AO1: Prediction &amp; Model Evaluation</h2>
<section id="fold-cross-validation" class="content-panel panel-small">
<h3>10-Fold Cross-Validation</h3>
<table class="caption-top">
<thead>
<tr class="header">
<th>Model</th>
<th style="text-align: right;">Mean ROC AUC</th>
<th style="text-align: right;">Standard Error</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>XGBoost</strong></td>
<td style="text-align: right;"><strong>0.622</strong></td>
<td style="text-align: right;">0.0027</td>
</tr>
<tr class="even">
<td>Lasso Logistic Regression</td>
<td style="text-align: right;">0.620</td>
<td style="text-align: right;">0.0024</td>
</tr>
<tr class="odd">
<td>Decision Tree</td>
<td style="text-align: right;">0.613</td>
<td style="text-align: right;">0.0029</td>
</tr>
<tr class="even">
<td>Random Forest</td>
<td style="text-align: right;">0.609</td>
<td style="text-align: right;">0.0022</td>
</tr>
</tbody>
</table>
<p><strong>Best Model:</strong> XGBoost</p>
<p>XGBoost achieved the highest ROC AUC, but its advantage over Lasso was only <strong>0.002</strong>, which was smaller than one standard error.</p>
<p><strong>Finding:</strong> More model complexity provided only a small improvement over Logistic Regression.</p>
</section>
</section>
<section id="ao1-model-interpretation" class="slide level2 importance-slide dense-slide" data-background-image="assets/importance-topic.png" data-background-size="cover" data-background-opacity="0.16">
<h2>AO1: Model Interpretation</h2>
<div class="content-panel panel-xs">
<p><strong>Variable Importance</strong></p>
<ul>
<li><strong>Prior total spending</strong> was the strongest feature</li>
<li>Online purchase share and age also contributed</li>
<li>Purchasing behavior was more informative than demographics</li>
</ul>
<p><strong>Partial Dependence</strong></p>
<ul>
<li>Higher prior spending generally increased High-Spender probability</li>
</ul>
<p><strong>SHAP</strong></p>
<ul>
<li>Unknown Fashion News status and prior spending had the largest average effects</li>
<li>“Unknown” represents missing information and should be interpreted carefully</li>
</ul>
</div>
</section>
<section id="ao1-summary-findings" class="slide level2 importance-slide dense-slide" data-background-image="assets/importance-topic.png" data-background-size="cover" data-background-opacity="0.16">
<h2>AO1: Summary Findings</h2>
<div class="content-panel panel-xs">
<p><strong>Key Findings</strong></p>
<ul>
<li><strong>XGBoost:</strong> highest CV ROC AUC (<strong>0.622</strong>)</li>
<li><strong>Lasso:</strong> nearly identical performance (<strong>0.620</strong>)</li>
<li><strong>Prior total spending:</strong> strongest XGBoost feature</li>
<li>Higher prior spending generally increased High-Spender probability</li>
<li>Purchasing behavior was more informative than Fashion News status</li>
</ul>
<p><strong>Business Takeaway</strong></p>
<ul>
<li>Focus on <strong>previous purchasing behavior</strong></li>
<li>Prioritize stronger spenders for personalized marketing</li>
<li>Use predictions as <strong>decision support</strong>, not perfect classifications</li>
</ul>
</div>
</section>
<section id="ao2-predicting-membership-status-from-spending-and-age" class="slide level2 importance-slide" data-background-image="assets/importance-topic.png" data-background-size="cover" data-background-opacity="0.16">
<h2>AO2: Predicting Membership Status from Spending and Age</h2>
<div class="content-panel panel-small">
<p><strong>Research Objective:</strong> Can spending behavior and age help explain which customers are more likely to leave the membership program?</p>
<p><strong>Lead:</strong> Rosarie Maramag</p>
<p><strong>ML Methods Used:</strong> Classification-Focused Methods — Multinomial Logistic Regression (predicting a 3-category outcome: ACTIVE, PRE-CREATE, LEFT CLUB)</p>
<p><strong>IV’s and DV’s:</strong> IV: <code>Total Spending</code>, <code>Purchase Frequency</code>, and <code>Age</code> (Continuous/Numerical)</p>
<p>DV: <code>Membership Status</code> (Categorical: ACTIVE, PRE-CREATE, LEFT CLUB)</p>
</div>
</section>
<section id="ao2-data-wrangling-visualization" class="slide level2 importance-slide" data-background-image="assets/importance-topic.png" data-background-size="cover" data-background-opacity="0.16">
<h2>AO2: Data Wrangling &amp; Visualization</h2>
<div class="content-panel panel-smaller">
<p><strong>Data wrangling:</strong> Linked customer records to transaction history using Customer IDs. Handled missing values in <code>Age</code> (~15,861 missing) and <code>Membership Status</code> (~6,062 missing). Since only 467 of 1.37M customers are LEFT CLUB (~0.03%), a simple random sample would have captured almost none of them — so a <strong>stratified sample</strong> was used instead: all available LEFT CLUB customers, plus a random sample of PRE-CREATE and ACTIVE customers, to ensure the rare class was represented. Aggregated total spend and purchase frequency per customer.</p>
<p><strong>Final sample:</strong> 4,333 ACTIVE · 2,214 PRE-CREATE · 323 LEFT CLUB</p>
<p><strong>Data visualization:</strong> A stacked bar chart showing the distribution of Membership Status across Age Brackets, and a box plot comparing total spending across membership groups.</p>
</div>
</section>
<section id="ao2-model-fitting" class="slide level2 importance-slide" data-background-image="assets/importance-topic.png" data-background-size="cover" data-background-opacity="0.16">
<h2>AO2: Model Fitting</h2>
<div class="content-panel panel-small">
<p><strong>Data splitting:</strong> 80/20 train-test split, stratified by membership status to preserve class proportions in both sets.</p>
<p><strong>Recipe:</strong> Predictors (age, total spend, purchase frequency) were normalized (centered and scaled) before modeling.</p>
<p><strong>Model specification:</strong> Multinomial logistic regression (<code>multinom_reg()</code> via the <code>nnet</code> engine), predicting membership status from age, total spend, and purchase frequency.</p>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href=""></a>model_recipe <span class="ot">&lt;-</span> <span class="fu">recipe</span>(membership_status <span class="sc">~</span> age <span class="sc">+</span> total_spend <span class="sc">+</span> purchase_freq,</span>
<span id="cb1-2"><a href=""></a>                        <span class="at">data =</span> customer_data) <span class="sc">%&gt;%</span></span>
<span id="cb1-3"><a href=""></a>  <span class="fu">step_normalize</span>(<span class="fu">all_numeric_predictors</span>())</span>
<span id="cb1-4"><a href=""></a></span>
<span id="cb1-5"><a href=""></a>model_spec <span class="ot">&lt;-</span> <span class="fu">multinom_reg</span>() <span class="sc">%&gt;%</span></span>
<span id="cb1-6"><a href=""></a>  <span class="fu">set_engine</span>(<span class="st">"nnet"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-7"><a href=""></a>  <span class="fu">set_mode</span>(<span class="st">"classification"</span>)</span>
<span id="cb1-8"><a href=""></a></span>
<span id="cb1-9"><a href=""></a>data_split <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(customer_data, <span class="at">prop =</span> <span class="fl">0.8</span>, <span class="at">strata =</span> membership_status)</span>
<span id="cb1-10"><a href=""></a>train_data <span class="ot">&lt;-</span> <span class="fu">training</span>(data_split)</span>
<span id="cb1-11"><a href=""></a>test_data  <span class="ot">&lt;-</span> <span class="fu">testing</span>(data_split)</span>
<span id="cb1-12"><a href=""></a></span>
<span id="cb1-13"><a href=""></a>final_model <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span></span>
<span id="cb1-14"><a href=""></a>  <span class="fu">add_recipe</span>(model_recipe) <span class="sc">%&gt;%</span></span>
<span id="cb1-15"><a href=""></a>  <span class="fu">add_model</span>(model_spec) <span class="sc">%&gt;%</span></span>
<span id="cb1-16"><a href=""></a>  <span class="fu">fit</span>(<span class="at">data =</span> train_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="ao2-prediction-and-model-evaluation" class="slide level2 importance-slide" data-background-image="assets/importance-topic.png" data-background-size="cover" data-background-opacity="0.16">
<h2>AO2: Prediction and Model Evaluation</h2>
<div class="content-panel panel-small">
<p>The model was evaluated on the held-out 20% test set.</p>
<p><strong>Accuracy: 65.5%</strong> — the model correctly classified a customer’s membership status about two-thirds of the time.</p>
<p><strong>Kappa: 0.158</strong> — a low-to-moderate score, indicating the model performs only somewhat better than chance once class imbalance is accounted for. This reflects how difficult it genuinely is to predict a rare outcome like leaving the club from just three variables.</p>
</div>
</section>
<section id="ao2-interpretation" class="slide level2 importance-slide" data-background-image="assets/importance-topic.png" data-background-size="cover" data-background-opacity="0.16">
<h2>AO2: Interpretation</h2>
<div class="content-panel panel-small">
<p>Coefficients show how each variable shifts the odds of a customer’s status relative to ACTIVE members:</p>
<ul>
<li><strong>Purchase frequency</strong> was negatively associated with both PRE-CREATE and LEFT CLUB status — customers who purchase less often are more likely to fall into either non-active group.</li>
<li><strong>Total spending</strong> was positively associated with LEFT CLUB status — surprisingly, higher total spending did not clearly predict staying active.</li>
<li><strong>Age</strong> had the smallest effect of the three predictors on LEFT CLUB status.</li>
</ul>
<p>This suggests <strong>how often</strong> a customer buys may be a stronger signal of disengagement than <strong>how much</strong> they’ve spent historically.</p>
</div>
</section>
<section id="ao2-summary-findings" class="slide level2 importance-slide" data-background-image="assets/importance-topic.png" data-background-size="cover" data-background-opacity="0.16">
<h2>AO2: Summary Findings</h2>
<div class="content-panel panel-small">
<p>Spending behavior and age can partially explain membership status, but the relationship is more nuanced than expected. Purchase <strong>frequency</strong>, not total spend, was the more consistent signal of disengagement — challenging the common assumption that active members are simply defined by how much they spend.</p>
<p>The model’s moderate accuracy (65.5%) and low Kappa (0.158) suggest membership status is difficult to predict from these three variables alone, and that behavioral factors beyond spending and age (e.g., recency of last purchase, channel preference) may better explain why customers leave.</p>
<p><strong>Business takeaway:</strong> H&amp;M’s retention efforts may benefit more from monitoring <em>purchase frequency trends</em> per customer than from spending thresholds alone.</p>
</div>
</section>
<section id="ro3-sales-channel-and-spending" class="slide level2 importance-slide" data-background-image="assets/importance-topic.png" data-background-size="cover" data-background-opacity="0.16">
<h2>RO3: Sales Channel and Spending</h2>
<div class="content-panel panel-small">
<p><strong>Research Objective:</strong> Does the sales channel (online vs.&nbsp;store) relate to spending patterns?<br>
<strong>Lead:</strong> Michelle Diaz</p>
<p><strong>IV’s and DV’s:</strong><br>
IV: Sales channel (online vs.&nbsp;store)<br>
DV: Price / basket size (spend per transaction or per customer)</p>
<p><strong>Plan for data wrangling:</strong><br>
Join transaction-level data with customer and article metadata as needed, confirm sales_channel_id is correctly coded, aggregate price to customer-level spend, and check for missing or invalid values.</p>
<p><strong>Plan for data visualization:</strong><br>
Boxplot or violin plot comparing price distribution across channels, and a bar chart comparing average spend per customer by channel.</p>
</div>
</section>
<section id="ro3-sales-channel-and-spending-ml-method" class="slide level2 importance-slide" data-background-image="assets/importance-topic.png" data-background-size="cover" data-background-opacity="0.16">
<h2>RO3: Sales Channel and Spending – ML Method</h2>
<div class="content-panel panel-small">
<p><strong>Method used:</strong> Regression tree (CART), with bagged tree and random forest as comparison ensembles</p>
<p><strong>Why regression, not classification:</strong> DV (price / spend) is continuous, not a category</p>
<p><strong>Why a tree-based method:</strong> Allows non-linear splits and interactions between channel, product group, age, membership status, and news subscription without assuming a linear relationship</p>
</div>
</section>
<section id="ro3-model-fitting" class="slide level2 importance-slide" data-background-image="assets/importance-topic.png" data-background-size="cover" data-background-opacity="0.16">
<h2>RO3: Model Fitting</h2>
<div class="content-panel panel-small">
<p><strong>Data:</strong> ~75,000 row sample of H&amp;M transactions, joined to customer and article metadata</p>
<p><strong>Split:</strong> 75% train / 25% test, stratified by price</p>
<p><strong>Recipe:</strong> price ~ sales_channel_id + age + club_member_status + fashion_news_frequency + product_group_name</p>
<p><strong>Model spec:</strong> Decision tree (rpart engine), compared against bagged tree and random forest (ranger engine), evaluated with 10-fold cross-validation</p>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href=""></a>hm_split <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(hm_sample, <span class="at">prop =</span> <span class="fl">0.75</span>, <span class="at">strata =</span> price)</span>
<span id="cb2-2"><a href=""></a>hm_train <span class="ot">&lt;-</span> <span class="fu">training</span>(hm_split)</span>
<span id="cb2-3"><a href=""></a>hm_test  <span class="ot">&lt;-</span> <span class="fu">testing</span>(hm_split)</span>
<span id="cb2-4"><a href=""></a></span>
<span id="cb2-5"><a href=""></a>hm_recipe <span class="ot">&lt;-</span> <span class="fu">recipe</span>(price <span class="sc">~</span> sales_channel_id <span class="sc">+</span> age <span class="sc">+</span> club_member_status <span class="sc">+</span></span>
<span id="cb2-6"><a href=""></a>                       fashion_news_frequency <span class="sc">+</span> product_group_name,</span>
<span id="cb2-7"><a href=""></a>                     <span class="at">data =</span> hm_train)</span>
<span id="cb2-8"><a href=""></a></span>
<span id="cb2-9"><a href=""></a>tree_spec <span class="ot">&lt;-</span> <span class="fu">decision_tree</span>() <span class="sc">|&gt;</span></span>
<span id="cb2-10"><a href=""></a>  <span class="fu">set_engine</span>(<span class="st">"rpart"</span>) <span class="sc">|&gt;</span></span>
<span id="cb2-11"><a href=""></a>  <span class="fu">set_mode</span>(<span class="st">"regression"</span>)</span>
<span id="cb2-12"><a href=""></a></span>
<span id="cb2-13"><a href=""></a>tree_fit <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">|&gt;</span></span>
<span id="cb2-14"><a href=""></a>  <span class="fu">add_recipe</span>(hm_recipe) <span class="sc">|&gt;</span></span>
<span id="cb2-15"><a href=""></a>  <span class="fu">add_model</span>(tree_spec) <span class="sc">|&gt;</span></span>
<span id="cb2-16"><a href=""></a>  <span class="fu">fit</span>(<span class="at">data =</span> hm_train)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="ro3-prediction-and-model-evaluation" class="slide level2 importance-slide" data-background-image="assets/importance-topic.png" data-background-size="cover" data-background-opacity="0.16">
<h2>RO3: Prediction and Model Evaluation</h2>
<div class="content-panel panel-small">
<p><strong>Test set performance:</strong></p>
<p>RMSE = 0.0179 R-squared = 0.0884</p>
<p><strong>What this means:</strong> The model explains only about 9% of the variation in price. Channel, age, product group, and membership status together are weak predictors of spend, most of the variation comes from factors not captured in this data.</p>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href=""></a>tree_preds <span class="ot">&lt;-</span> <span class="fu">predict</span>(tree_fit, hm_test) <span class="sc">|&gt;</span></span>
<span id="cb3-2"><a href=""></a>  <span class="fu">bind_cols</span>(hm_test)</span>
<span id="cb3-3"><a href=""></a></span>
<span id="cb3-4"><a href=""></a>tree_preds <span class="sc">|&gt;</span></span>
<span id="cb3-5"><a href=""></a>  <span class="fu">metrics</span>(<span class="at">truth =</span> price, <span class="at">estimate =</span> .pred)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="ro3-interpretation" class="slide level2 importance-slide" data-background-image="assets/importance-topic.png" data-background-size="cover" data-background-opacity="0.16">
<h2>RO3: Interpretation</h2>
<div class="content-panel panel-small">
<p><strong>Single tree:</strong> Splits entirely on product_group_name. Sales channel is never chosen as a splitting variable.</p>
<p><strong>Random forest variable importance:</strong> product_group_name is by far the strongest predictor. sales_channel_id ranks second, well behind product group. age, fashion_news_frequency, and club_member_status contribute very little.</p>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href=""></a><span class="fu">rpart.plot</span>(tree_fit<span class="sc">$</span>fit<span class="sc">$</span>fit<span class="sc">$</span>fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href=""></a>rf_spec <span class="ot">&lt;-</span> <span class="fu">rand_forest</span>() <span class="sc">|&gt;</span></span>
<span id="cb5-2"><a href=""></a>  <span class="fu">set_engine</span>(<span class="st">"ranger"</span>, <span class="at">importance =</span> <span class="st">"impurity"</span>) <span class="sc">|&gt;</span></span>
<span id="cb5-3"><a href=""></a>  <span class="fu">set_mode</span>(<span class="st">"regression"</span>)</span>
<span id="cb5-4"><a href=""></a></span>
<span id="cb5-5"><a href=""></a>rf_fit <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">|&gt;</span></span>
<span id="cb5-6"><a href=""></a>  <span class="fu">add_recipe</span>(hm_recipe) <span class="sc">|&gt;</span></span>
<span id="cb5-7"><a href=""></a>  <span class="fu">add_model</span>(rf_spec) <span class="sc">|&gt;</span></span>
<span id="cb5-8"><a href=""></a>  <span class="fu">fit</span>(<span class="at">data =</span> hm_train)</span>
<span id="cb5-9"><a href=""></a></span>
<span id="cb5-10"><a href=""></a>rf_fit <span class="sc">|&gt;</span></span>
<span id="cb5-11"><a href=""></a>  <span class="fu">extract_fit_parsnip</span>() <span class="sc">|&gt;</span></span>
<span id="cb5-12"><a href=""></a>  vip<span class="sc">::</span><span class="fu">vip</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="ro3-summary-findings" class="slide level2 importance-slide" data-background-image="assets/importance-topic.png" data-background-size="cover" data-background-opacity="0.16">
<h2>RO3: Summary Findings</h2>
<div class="content-panel panel-small">
<p><strong>Does sales channel relate to spending? Not meaningfully.</strong></p>
<p>The regression tree split entirely on product group, never on sales channel. The random forest ranked sales channel second in importance, but far behind product group.</p>
<p><strong>What actually drives spend:</strong> What a customer buys (product group) matters far more than where they buy it (online vs.&nbsp;in store).</p>
<p><strong>Caveat:</strong> Overall model performance is weak (R-squared = 0.0884), so even product group alone does not strongly predict price. Spend is likely driven by factors outside this dataset, such as promotions, loyalty behavior, or individual preference.</p>
</div>
</section>
<section id="ao4-predicting-future-rfm-value" class="slide level2 importance-slide" data-background-image="assets/importance-topic.png" data-background-size="cover" data-background-opacity="0.16">
<h2>AO4: Predicting Future RFM Value</h2>
<div class="content-panel panel-small">
<p><strong>Research Objective:</strong><br>
Can historical customer behavior predict a customer’s future RFM value?</p>
<p><strong>Lead:</strong> Frank Renn</p>
<p><strong>Machine Learning Methods</strong></p>
<ul>
<li>Classification Tree</li>
<li>Bagged Trees</li>
<li>Random Forest</li>
<li>Boosted Tree</li>
</ul>
<p><strong>Outcome:</strong><br>
Inactive · Low Value · Mid Value · High Value</p>
<p><strong>Business Goal:</strong><br>
Identify customers for retention, growth, and reactivation campaigns.</p>
</div>
</section>
<section id="ao4-data-wrangling-visualization" class="slide level2 importance-slide dense-slide" data-background-image="assets/importance-topic.png" data-background-size="cover" data-background-opacity="0.16">
<h2>AO4: Data Wrangling &amp; Visualization</h2>
<div class="content-panel">
<h3 id="data-wrangling-1">Data Wrangling</h3>
<ul>
<li>Aggregated transactions to the <strong>customer level</strong></li>
<li>Created historical <strong>Recency, Frequency, and Monetary</strong> measures</li>
<li>Added average price, number of items, online share, active months, and purchase span</li>
<li>Joined age, membership status, and fashion-news variables</li>
<li>Used future purchasing behavior to create the target RFM class</li>
</ul>
<h3 id="time-periods">Time Periods</h3>
<p><strong>Historical Features:</strong> Jun 2019 – May 2020<br>
<strong>Future Outcome:</strong> Jun 2020 onward</p>
<h3 id="visualization-finding">Visualization Finding</h3>
<p>Frequency and monetary behavior showed substantial overlap across future RFM groups, indicating that the four customer classes would not be perfectly separable.</p>
</div>
</section>
<section id="ao4-model-fitting" class="slide level2 importance-slide dense-slide" data-background-image="assets/importance-topic.png" data-background-size="cover" data-background-opacity="0.16">
<h2>AO4: Model Fitting</h2>
<div class="content-panel">
<h3 id="data-splitting">Data Splitting</h3>
<ul>
<li><strong>80% training / 20% testing</strong></li>
<li>Stratified by future RFM class</li>
<li>Up to <strong>1,500 customers per class</strong></li>
<li>Approximately balanced four-class sample</li>
</ul>
<h3 id="recipe-creation">Recipe Creation</h3>
<ul>
<li>Median imputation for missing numeric predictors</li>
<li>Unknown and new categorical levels handled</li>
<li>Zero-variance predictors removed</li>
<li>One-hot encoding applied for XGBoost</li>
</ul>
<h3 id="model-specification">Model Specification</h3>
<table class="caption-top">
<thead>
<tr class="header">
<th>Model</th>
<th>Approach</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Classification Tree</td>
<td>Single interpretable tree</td>
</tr>
<tr class="even">
<td>Bagged Trees</td>
<td>Multiple bootstrap trees</td>
</tr>
<tr class="odd">
<td>Random Forest</td>
<td>Bagging + random predictor selection</td>
</tr>
<tr class="even">
<td>Boosted Tree</td>
<td>Sequential error-correcting trees</td>
</tr>
</tbody>
</table>
<p><strong>Validation:</strong> 10-fold stratified cross-validation</p>
</div>
</section>
<section id="ao4-prediction-model-evaluation" class="slide level2 importance-slide dense-slide" data-background-image="assets/importance-topic.png" data-background-size="cover" data-background-opacity="0.16">
<h2>AO4: Prediction &amp; Model Evaluation</h2>
<div class="content-panel">
<h3 id="classification-tree-test-set">Classification Tree — Test Set</h3>
<table class="caption-top">
<thead>
<tr class="header">
<th>Metric</th>
<th style="text-align: right;">Result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Accuracy</td>
<td style="text-align: right;"><strong>41.1%</strong></td>
</tr>
<tr class="even">
<td>Macro Sensitivity</td>
<td style="text-align: right;"><strong>41.1%</strong></td>
</tr>
<tr class="odd">
<td>Macro Specificity</td>
<td style="text-align: right;"><strong>80.4%</strong></td>
</tr>
<tr class="even">
<td>Multiclass ROC AUC</td>
<td style="text-align: right;"><strong>0.673</strong></td>
</tr>
</tbody>
</table>
<p>With four balanced classes, random guessing would produce approximately <strong>25% accuracy</strong>.</p>
<h3 id="cross-validated-model-comparison">Cross-Validated Model Comparison</h3>
<table class="caption-top">
<thead>
<tr class="header">
<th>Model</th>
<th>Result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Boosted Tree</strong></td>
<td><strong>42.4% Accuracy / 0.695 AUC</strong></td>
</tr>
<tr class="even">
<td>Classification Tree</td>
<td>41.7% Accuracy / 0.674 AUC</td>
</tr>
<tr class="odd">
<td>Random Forest</td>
<td>0.687 AUC</td>
</tr>
<tr class="even">
<td>Bagged Trees</td>
<td>Evaluated on same CV folds</td>
</tr>
</tbody>
</table>
<p><strong>Best Model:</strong> <strong>Boosted Tree</strong></p>
</div>
</section>
<section id="ao4-interpretation" class="slide level2 importance-slide dense-slide" data-background-image="assets/importance-topic.png" data-background-size="cover" data-background-opacity="0.16">
<h2>AO4: Interpretation</h2>
<div class="content-panel">
<h3 id="recall-by-customer-segment">Recall by Customer Segment</h3>
<table class="caption-top">
<thead>
<tr class="header">
<th>Segment</th>
<th style="text-align: right;">Recall</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Inactive</strong></td>
<td style="text-align: right;"><strong>62.7%</strong></td>
</tr>
<tr class="even">
<td><strong>High Value</strong></td>
<td style="text-align: right;"><strong>52.0%</strong></td>
</tr>
<tr class="odd">
<td>Low Value</td>
<td style="text-align: right;">27.7%</td>
</tr>
<tr class="even">
<td>Mid Value</td>
<td style="text-align: right;">22.0%</td>
</tr>
</tbody>
</table>
<h3 id="interpretation">Interpretation</h3>
<ul>
<li><strong>Inactive</strong> customers were easiest to identify</li>
<li><strong>High Value</strong> customers were also predicted relatively well</li>
<li>Mid and Low Value customers had more overlapping historical behavior</li>
<li>Extreme customer groups were easier to distinguish than middle-value groups</li>
<li>Random Forest <strong>permutation importance</strong> was used to identify influential predictors</li>
<li>Historical purchasing behavior provided stronger predictive information than profile variables alone</li>
</ul>
</div>
</section>
<section id="ao4-tree-complexity-pruning" class="slide level2 importance-slide dense-slide" data-background-image="assets/importance-topic.png" data-background-size="cover" data-background-opacity="0.16">
<h2>AO4: Tree Complexity &amp; Pruning</h2>
<div class="content-panel">
<h3 id="overfitted-tree">Overfitted Tree</h3>
<p><strong>Cost Complexity: <code>cp = 0.0001</code></strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Metric</th>
<th style="text-align: right;">Result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Training AUC</td>
<td style="text-align: right;"><strong>1.00</strong></td>
</tr>
<tr class="even">
<td>Testing AUC</td>
<td style="text-align: right;">~<strong>0.55</strong></td>
</tr>
</tbody>
</table>
<p>The large gap shows severe <strong>overfitting</strong>.</p>
<h3 id="best-pruning-level">Best Pruning Level</h3>
<p><strong>Cost Complexity: <code>cp ≈ 0.001</code></strong></p>
<ul>
<li>Testing AUC: ~<strong>0.68</strong></li>
<li>Final tree: <strong>55 leaf nodes</strong></li>
</ul>
<p><strong>Finding:</strong><br>
Moderate pruning improved generalization by reducing unnecessary model complexity.</p>
</div>
</section>
<section id="ao4-summary-findings" class="slide level2 importance-slide dense-slide" data-background-image="assets/importance-topic.png" data-background-size="cover" data-background-opacity="0.16">
<h2>AO4: Summary Findings</h2>
<div class="content-panel">
<h3 id="key-findings">Key Findings</h3>
<ul>
<li>Historical customer behavior provided a <strong>moderate signal</strong> of future RFM value</li>
<li>Classification Tree achieved <strong>41.1% test accuracy / 0.673 AUC</strong></li>
<li>Boosted Tree performed best with <strong>42.4% CV accuracy / 0.695 AUC</strong></li>
<li>Inactive customers had the highest recall at <strong>62.7%</strong></li>
<li>High Value customers achieved <strong>52.0% recall</strong></li>
<li>Mid Value customers were hardest to identify at <strong>22.0% recall</strong></li>
<li>Moderate pruning reduced overfitting and improved generalization</li>
</ul>
<h3 id="business-takeaway">Business Takeaway</h3>
<p><strong>High Value</strong> → Loyalty &amp; retention<br>
<strong>Mid / Low Value</strong> → Engagement &amp; growth<br>
<strong>Inactive</strong> → Reactivation &amp; win-back</p>
<p>Predicted RFM value can help H&amp;M prioritize customer targeting, but the model should be used as a <strong>decision-support tool rather than a perfect classification system</strong>.</p>
</div>
</section>
<section id="ro5-purchase-timing-patterns-across-segments" class="slide level2 importance-slide" data-background-image="assets/importance-topic.png" data-background-size="cover" data-background-opacity="0.16">
<h2>RO5: Purchase Timing Patterns Across Segments</h2>
<div class="content-panel panel-small">
<p><strong>Research Objective:</strong> Do purchase timing patterns differ across customer segments?<br>
<strong>Lead:</strong> Daisy Hernandez</p>
<p><strong>IV’s and DV’s:</strong><br>
IV: Customer segment (e.g., RFM group or demographic segment)<br>
DV: Purchase timing (day of week, month/season, time between purchases)</p>
<p><strong>Plan for data wrangling:</strong><br>
Extract date components (day of week, month, season) from transaction timestamps, join transactions with customer segment labels, and aggregate purchase counts and average time-between-purchases by segment and time period.</p>
<p><strong>Plan for data visualization:</strong><br>
A heatmap of purchase frequency by day of week and segment, and a line chart showing purchase volume trends over time (by month/season) across customer segments.</p>
</div>
</section>
<section id="ao5-purchase-timing-ml-method" class="slide level2 importance-slide" data-background-image="assets/importance-topic.png" data-background-size="cover" data-background-opacity="0.16">
<h2>AO5: Purchase Timing – ML Method</h2>
<div class="content-panel panel-small">
<p><strong>Method used:</strong> Regression tree (rpart), with random forest (ranger) as a comparison ensemble</p>
<p><strong>Why regression, not classification:</strong> DV (average days between purchases) is continuous, not a category</p>
<p><strong>Why this approach:</strong></p>
<ul>
<li>Compares a simple, interpretable single tree against an ensemble method</li>
<li>Tests whether purchase count and age group can predict timing patterns</li>
</ul>
</div>
</section>
<section id="ao5-data-wrangling-visualization" class="slide level2 importance-slide" data-background-image="assets/importance-topic.png" data-background-size="cover" data-background-opacity="0.16">
<h2>AO5: Data Wrangling &amp; Visualization</h2>
<div class="content-panel panel-small">
<p><strong>Data:</strong> A 75,000-row sample of H&amp;M transactions, joined with customer metadata</p>
<p><strong>Wrangling steps:</strong></p>
<ul>
<li>Calculated the time gap between each customer’s consecutive purchases</li>
<li>Aggregated to average days between purchases per customer</li>
<li>Filtered to customers with more than one purchase</li>
<li>Joined with age group segments (Under 25, 25-39, 40-59, 60+)</li>
</ul>
<p><strong>Visualization finding:</strong> A heatmap of purchase frequency by day of week and age group shows the 60+ age group purchasing noticeably more often than other segments, fairly consistently across all days of the week.</p>
</div>

<img data-src="assets/ro5_heatmap.png" class="r-stretch"></section>
<section id="ao5-model-fitting" class="slide level2 importance-slide" data-background-image="assets/importance-topic.png" data-background-size="cover" data-background-opacity="0.16">
<h2>AO5: Model Fitting</h2>
<div class="content-panel panel-small">
<p><strong>Data splitting:</strong> 75% train / 25% test, stratified by average days between purchases</p>
<p><strong>Recipe:</strong> avg_days_between_purchases ~ age_group + n_purchases</p>
<p><strong>Model spec:</strong></p>
<ul>
<li>Decision tree (rpart engine)</li>
<li>Compared against random forest (ranger engine)</li>
</ul>
</div>
</section>
<section id="ao5-prediction-and-model-evaluation" class="slide level2 importance-slide" data-background-image="assets/importance-topic.png" data-background-size="cover" data-background-opacity="0.16">
<h2>AO5: Prediction and Model Evaluation</h2>
<div class="content-panel panel-small">
<p><strong>Random forest test set performance:</strong></p>
<ul>
<li>RMSE = 167</li>
<li>R-squared = 0.0135</li>
<li>MAE = 136</li>
</ul>
<p><strong>What this means:</strong> The model explains only about 1.3% of the variation in average time between purchases, most of the variation comes from factors not captured in this data.</p>
</div>

<img data-src="assets/ro5_metrics.png" class="r-stretch"></section>
<section id="ao5-interpretation" class="slide level2 importance-slide" data-background-image="assets/importance-topic.png" data-background-size="cover" data-background-opacity="0.16">
<h2>AO5: Interpretation</h2>
<div class="content-panel panel-small">
<p><strong>Purchase count (n_purchases):</strong> Overwhelmingly the strongest predictor, roughly 25 to 30 times higher importance than any age group category</p>
<p><strong>Age group:</strong> Contributed very little across all four brackets, similarly low importance throughout</p>
<p><strong>Takeaway:</strong> How often a customer has purchased matters far more than their age when predicting time between purchases</p>
</div>

<img data-src="assets/ro5_importance.png" class="r-stretch"></section>
<section id="ao5-summary-findings" class="slide level2 importance-slide" data-background-image="assets/importance-topic.png" data-background-size="cover" data-background-opacity="0.16">
<h2>AO5: Summary Findings</h2>
<div class="content-panel panel-small">
<p><strong>Do purchase timing patterns differ across customer segments? Not by age, meaningfully.</strong></p>
<ul>
<li>Random forest explained only 1.3% of the variation in time between purchases</li>
<li>Purchase count dominated the model</li>
<li>Age group added almost nothing</li>
</ul>
<p><strong>Business takeaway:</strong> H&amp;M’s timing-based campaigns are better targeted using a customer’s purchase history rather than their age bracket. Age alone is not a useful segment for timing predictions.</p>
</div>
</section>
<section id="appendix" class="slide level2 importance-slide" data-background-image="assets/importance-topic.png" data-background-size="cover" data-background-opacity="0.16">
<h2>Appendix</h2>
<div class="content-panel panel-small">
<h3 id="project-resources">Project Resources</h3>
<p><strong>GitHub Repository</strong><br>
<a href="https://github.com/MichelleeeDiazzz/IBM-6540-Group-Project-">View Group Project Repository</a></p>
<p><strong>Presentation Slides</strong></p>
<h3 id="deployed-machine-learning-model">Deployed Machine Learning Model</h3>
<p><strong>H&amp;M High-Spender Predictor — Gigi Brunel</strong></p>
<p><a href="https://qnca96-gigi-brunel.shinyapps.io/hm-high-spender-predictor/">Open Interactive XGBoost Prediction Dashboard</a></p>
<p><strong>Purpose:</strong> Enter different customer characteristics to estimate the probability that an H&amp;M customer will become a future high spender.</p>
<p><strong>Membership Status Predictor — Rosarie Maramag</strong></p>
<p><a href="https://rmaramag.shinyapps.io/membership-shiny-app/">Open Interactive Membership Status Prediction Dashboard</a></p>
<p><strong>Purpose:</strong> Enter a customer’s age, total spending, and purchase frequency to see the predicted membership status (Active, Pre-Create, or Left Club) and the model’s confidence in each outcome.</p>
</div>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="Group4-Slides_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="Group4-Slides_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="Group4-Slides_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="Group4-Slides_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="Group4-Slides_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="Group4-Slides_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="Group4-Slides_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="Group4-Slides_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="Group4-Slides_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="Group4-Slides_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': false,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: true,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'fade',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 6.0e-2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>